apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: "system"
objects:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: pv${PV}
  spec:
    accessModes:
    - ReadWriteOnce
    - ReadWriteMany
    capacity:
      storage: 1Gi
    persistentVolumeReclaimPolicy: Recycle
    hostPath:
      path: ${PATH}/${PV}
parameters:
- name: PV
  required: true
- name: PATH
  value: /var/lib/docker/pv
  required: true
